/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.Public;
import com.example.backend.jooq.tables.GenerationLogs.GenerationLogsPath;
import com.example.backend.jooq.tables.Users.UsersPath;
import com.example.backend.jooq.tables.records.DailyReportsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DailyReports extends TableImpl<DailyReportsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.daily_reports</code>
     */
    public static final DailyReports DAILY_REPORTS = new DailyReports();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DailyReportsRecord> getRecordType() {
        return DailyReportsRecord.class;
    }

    /**
     * The column <code>public.daily_reports.id</code>.
     */
    public final TableField<DailyReportsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.daily_reports.user_id</code>.
     */
    public final TableField<DailyReportsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.daily_reports.report_date</code>.
     */
    public final TableField<DailyReportsRecord, LocalDate> REPORT_DATE = createField(DSL.name("report_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.daily_reports.raw_data</code>.
     */
    public final TableField<DailyReportsRecord, JSONB> RAW_DATA = createField(DSL.name("raw_data"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.daily_reports.generated_content</code>.
     */
    public final TableField<DailyReportsRecord, String> GENERATED_CONTENT = createField(DSL.name("generated_content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.daily_reports.edited_content</code>.
     */
    public final TableField<DailyReportsRecord, String> EDITED_CONTENT = createField(DSL.name("edited_content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.daily_reports.final_content</code>.
     */
    public final TableField<DailyReportsRecord, String> FINAL_CONTENT = createField(DSL.name("final_content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.daily_reports.status</code>.
     */
    public final TableField<DailyReportsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'DRAFT'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.daily_reports.generation_count</code>.
     */
    public final TableField<DailyReportsRecord, Integer> GENERATION_COUNT = createField(DSL.name("generation_count"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.daily_reports.additional_notes</code>.
     */
    public final TableField<DailyReportsRecord, String> ADDITIONAL_NOTES = createField(DSL.name("additional_notes"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.daily_reports.created_at</code>.
     */
    public final TableField<DailyReportsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.daily_reports.updated_at</code>.
     */
    public final TableField<DailyReportsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private DailyReports(Name alias, Table<DailyReportsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DailyReports(Name alias, Table<DailyReportsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.daily_reports</code> table reference
     */
    public DailyReports(String alias) {
        this(DSL.name(alias), DAILY_REPORTS);
    }

    /**
     * Create an aliased <code>public.daily_reports</code> table reference
     */
    public DailyReports(Name alias) {
        this(alias, DAILY_REPORTS);
    }

    /**
     * Create a <code>public.daily_reports</code> table reference
     */
    public DailyReports() {
        this(DSL.name("daily_reports"), null);
    }

    public <O extends Record> DailyReports(Table<O> path, ForeignKey<O, DailyReportsRecord> childPath, InverseForeignKey<O, DailyReportsRecord> parentPath) {
        super(path, childPath, parentPath, DAILY_REPORTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DailyReportsPath extends DailyReports implements Path<DailyReportsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DailyReportsPath(Table<O> path, ForeignKey<O, DailyReportsRecord> childPath, InverseForeignKey<O, DailyReportsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DailyReportsPath(Name alias, Table<DailyReportsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DailyReportsPath as(String alias) {
            return new DailyReportsPath(DSL.name(alias), this);
        }

        @Override
        public DailyReportsPath as(Name alias) {
            return new DailyReportsPath(alias, this);
        }

        @Override
        public DailyReportsPath as(Table<?> alias) {
            return new DailyReportsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DAILY_REPORTS_REPORT_DATE, Indexes.IDX_DAILY_REPORTS_USER_DATE, Indexes.IDX_DAILY_REPORTS_USER_ID);
    }

    @Override
    public UniqueKey<DailyReportsRecord> getPrimaryKey() {
        return Keys.DAILY_REPORTS_PKEY;
    }

    @Override
    public List<ForeignKey<DailyReportsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DAILY_REPORTS__DAILY_REPORTS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.DAILY_REPORTS__DAILY_REPORTS_USER_ID_FKEY, null);

        return _users;
    }

    private transient GenerationLogsPath _generationLogs;

    /**
     * Get the implicit to-many join path to the
     * <code>public.generation_logs</code> table
     */
    public GenerationLogsPath generationLogs() {
        if (_generationLogs == null)
            _generationLogs = new GenerationLogsPath(this, null, Keys.GENERATION_LOGS__GENERATION_LOGS_REPORT_ID_FKEY.getInverseKey());

        return _generationLogs;
    }

    @Override
    public List<Check<DailyReportsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("daily_reports_status_check"), "(((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'EDITED'::character varying, 'APPROVED'::character varying])::text[])))", true)
        );
    }

    @Override
    public DailyReports as(String alias) {
        return new DailyReports(DSL.name(alias), this);
    }

    @Override
    public DailyReports as(Name alias) {
        return new DailyReports(alias, this);
    }

    @Override
    public DailyReports as(Table<?> alias) {
        return new DailyReports(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyReports rename(String name) {
        return new DailyReports(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyReports rename(Name name) {
        return new DailyReports(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DailyReports rename(Table<?> name) {
        return new DailyReports(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports where(Condition condition) {
        return new DailyReports(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyReports where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyReports where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyReports where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DailyReports where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DailyReports whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, UUID, LocalDate, JSONB, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super UUID, ? super UUID, ? super LocalDate, ? super JSONB, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super UUID, ? super UUID, ? super LocalDate, ? super JSONB, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
