/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.Public;
import com.example.backend.jooq.tables.Users.UsersPath;
import com.example.backend.jooq.tables.records.GithubCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubCredentials extends TableImpl<GithubCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.github_credentials</code>
     */
    public static final GithubCredentials GITHUB_CREDENTIALS = new GithubCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GithubCredentialsRecord> getRecordType() {
        return GithubCredentialsRecord.class;
    }

    /**
     * The column <code>public.github_credentials.id</code>.
     */
    public final TableField<GithubCredentialsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.github_credentials.user_id</code>.
     */
    public final TableField<GithubCredentialsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.github_credentials.api_key</code>.
     */
    public final TableField<GithubCredentialsRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.github_credentials.base_url</code>.
     */
    public final TableField<GithubCredentialsRecord, String> BASE_URL = createField(DSL.name("base_url"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("'https://api.github.com'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.github_credentials.owner</code>.
     */
    public final TableField<GithubCredentialsRecord, String> OWNER = createField(DSL.name("owner"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.github_credentials.repo</code>.
     */
    public final TableField<GithubCredentialsRecord, String> REPO = createField(DSL.name("repo"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.github_credentials.is_active</code>.
     */
    public final TableField<GithubCredentialsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.github_credentials.created_at</code>.
     */
    public final TableField<GithubCredentialsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.github_credentials.updated_at</code>.
     */
    public final TableField<GithubCredentialsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private GithubCredentials(Name alias, Table<GithubCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GithubCredentials(Name alias, Table<GithubCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.github_credentials</code> table reference
     */
    public GithubCredentials(String alias) {
        this(DSL.name(alias), GITHUB_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.github_credentials</code> table reference
     */
    public GithubCredentials(Name alias) {
        this(alias, GITHUB_CREDENTIALS);
    }

    /**
     * Create a <code>public.github_credentials</code> table reference
     */
    public GithubCredentials() {
        this(DSL.name("github_credentials"), null);
    }

    public <O extends Record> GithubCredentials(Table<O> path, ForeignKey<O, GithubCredentialsRecord> childPath, InverseForeignKey<O, GithubCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, GITHUB_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GithubCredentialsPath extends GithubCredentials implements Path<GithubCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GithubCredentialsPath(Table<O> path, ForeignKey<O, GithubCredentialsRecord> childPath, InverseForeignKey<O, GithubCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GithubCredentialsPath(Name alias, Table<GithubCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GithubCredentialsPath as(String alias) {
            return new GithubCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public GithubCredentialsPath as(Name alias) {
            return new GithubCredentialsPath(alias, this);
        }

        @Override
        public GithubCredentialsPath as(Table<?> alias) {
            return new GithubCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_GITHUB_CREDENTIALS_USER_ID, Indexes.IDX_GITHUB_CREDENTIALS_USER_UNIQUE);
    }

    @Override
    public UniqueKey<GithubCredentialsRecord> getPrimaryKey() {
        return Keys.GITHUB_CREDENTIALS_PKEY;
    }

    @Override
    public List<ForeignKey<GithubCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GITHUB_CREDENTIALS__GITHUB_CREDENTIALS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.GITHUB_CREDENTIALS__GITHUB_CREDENTIALS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public GithubCredentials as(String alias) {
        return new GithubCredentials(DSL.name(alias), this);
    }

    @Override
    public GithubCredentials as(Name alias) {
        return new GithubCredentials(alias, this);
    }

    @Override
    public GithubCredentials as(Table<?> alias) {
        return new GithubCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GithubCredentials rename(String name) {
        return new GithubCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GithubCredentials rename(Name name) {
        return new GithubCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GithubCredentials rename(Table<?> name) {
        return new GithubCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials where(Condition condition) {
        return new GithubCredentials(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GithubCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GithubCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GithubCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GithubCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GithubCredentials whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, UUID, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
