/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.JPublic;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.tables.JUsers.JUsersPath;
import com.example.backend.jooq.tables.records.JApiCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JApiCredentials extends TableImpl<JApiCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.api_credentials</code>
     */
    public static final JApiCredentials API_CREDENTIALS = new JApiCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JApiCredentialsRecord> getRecordType() {
        return JApiCredentialsRecord.class;
    }

    /**
     * The column <code>public.api_credentials.id</code>.
     */
    public final TableField<JApiCredentialsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.api_credentials.user_id</code>.
     */
    public final TableField<JApiCredentialsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.api_credentials.service_type</code>.
     */
    public final TableField<JApiCredentialsRecord, String> SERVICE_TYPE = createField(DSL.name("service_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.api_credentials.encrypted_key</code>.
     */
    public final TableField<JApiCredentialsRecord, String> ENCRYPTED_KEY = createField(DSL.name("encrypted_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.api_credentials.additional_config</code>.
     */
    public final TableField<JApiCredentialsRecord, JSONB> ADDITIONAL_CONFIG = createField(DSL.name("additional_config"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.api_credentials.is_active</code>.
     */
    public final TableField<JApiCredentialsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.api_credentials.created_at</code>.
     */
    public final TableField<JApiCredentialsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.api_credentials.updated_at</code>.
     */
    public final TableField<JApiCredentialsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private JApiCredentials(Name alias, Table<JApiCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JApiCredentials(Name alias, Table<JApiCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.api_credentials</code> table reference
     */
    public JApiCredentials(String alias) {
        this(DSL.name(alias), API_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.api_credentials</code> table reference
     */
    public JApiCredentials(Name alias) {
        this(alias, API_CREDENTIALS);
    }

    /**
     * Create a <code>public.api_credentials</code> table reference
     */
    public JApiCredentials() {
        this(DSL.name("api_credentials"), null);
    }

    public <O extends Record> JApiCredentials(Table<O> path, ForeignKey<O, JApiCredentialsRecord> childPath, InverseForeignKey<O, JApiCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, API_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JApiCredentialsPath extends JApiCredentials implements Path<JApiCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JApiCredentialsPath(Table<O> path, ForeignKey<O, JApiCredentialsRecord> childPath, InverseForeignKey<O, JApiCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JApiCredentialsPath(Name alias, Table<JApiCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JApiCredentialsPath as(String alias) {
            return new JApiCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public JApiCredentialsPath as(Name alias) {
            return new JApiCredentialsPath(alias, this);
        }

        @Override
        public JApiCredentialsPath as(Table<?> alias) {
            return new JApiCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_API_CREDENTIALS_SERVICE_TYPE, Indexes.IDX_API_CREDENTIALS_USER_ID, Indexes.IDX_API_CREDENTIALS_USER_SERVICE);
    }

    @Override
    public UniqueKey<JApiCredentialsRecord> getPrimaryKey() {
        return Keys.API_CREDENTIALS_PKEY;
    }

    @Override
    public List<ForeignKey<JApiCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.API_CREDENTIALS__API_CREDENTIALS_USER_ID_FKEY);
    }

    private transient JUsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public JUsersPath users() {
        if (_users == null)
            _users = new JUsersPath(this, Keys.API_CREDENTIALS__API_CREDENTIALS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public List<Check<JApiCredentialsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("api_credentials_service_type_check"), "(((service_type)::text = ANY ((ARRAY['GITHUB'::character varying, 'TOGGL'::character varying, 'NOTION'::character varying])::text[])))", true)
        );
    }

    @Override
    public JApiCredentials as(String alias) {
        return new JApiCredentials(DSL.name(alias), this);
    }

    @Override
    public JApiCredentials as(Name alias) {
        return new JApiCredentials(alias, this);
    }

    @Override
    public JApiCredentials as(Table<?> alias) {
        return new JApiCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JApiCredentials rename(String name) {
        return new JApiCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JApiCredentials rename(Name name) {
        return new JApiCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JApiCredentials rename(Table<?> name) {
        return new JApiCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials where(Condition condition) {
        return new JApiCredentials(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JApiCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JApiCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JApiCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JApiCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JApiCredentials whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, String, String, JSONB, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super UUID, ? super UUID, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super UUID, ? super UUID, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
