/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.JPublic;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.tables.JUsers.JUsersPath;
import com.example.backend.jooq.tables.records.JGithubCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JGithubCredentials extends TableImpl<JGithubCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.github_credentials</code>
     */
    public static final JGithubCredentials GITHUB_CREDENTIALS = new JGithubCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JGithubCredentialsRecord> getRecordType() {
        return JGithubCredentialsRecord.class;
    }

    /**
     * The column <code>public.github_credentials.id</code>.
     */
    public final TableField<JGithubCredentialsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.github_credentials.user_id</code>.
     */
    public final TableField<JGithubCredentialsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.github_credentials.api_key</code>.
     */
    public final TableField<JGithubCredentialsRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.github_credentials.base_url</code>.
     */
    public final TableField<JGithubCredentialsRecord, String> BASE_URL = createField(DSL.name("base_url"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("'https://api.github.com'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.github_credentials.owner</code>.
     */
    public final TableField<JGithubCredentialsRecord, String> OWNER = createField(DSL.name("owner"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.github_credentials.repo</code>.
     */
    public final TableField<JGithubCredentialsRecord, String> REPO = createField(DSL.name("repo"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.github_credentials.is_active</code>.
     */
    public final TableField<JGithubCredentialsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.github_credentials.created_at</code>.
     */
    public final TableField<JGithubCredentialsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.github_credentials.updated_at</code>.
     */
    public final TableField<JGithubCredentialsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private JGithubCredentials(Name alias, Table<JGithubCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JGithubCredentials(Name alias, Table<JGithubCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.github_credentials</code> table reference
     */
    public JGithubCredentials(String alias) {
        this(DSL.name(alias), GITHUB_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.github_credentials</code> table reference
     */
    public JGithubCredentials(Name alias) {
        this(alias, GITHUB_CREDENTIALS);
    }

    /**
     * Create a <code>public.github_credentials</code> table reference
     */
    public JGithubCredentials() {
        this(DSL.name("github_credentials"), null);
    }

    public <O extends Record> JGithubCredentials(Table<O> path, ForeignKey<O, JGithubCredentialsRecord> childPath, InverseForeignKey<O, JGithubCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, GITHUB_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JGithubCredentialsPath extends JGithubCredentials implements Path<JGithubCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JGithubCredentialsPath(Table<O> path, ForeignKey<O, JGithubCredentialsRecord> childPath, InverseForeignKey<O, JGithubCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JGithubCredentialsPath(Name alias, Table<JGithubCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JGithubCredentialsPath as(String alias) {
            return new JGithubCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public JGithubCredentialsPath as(Name alias) {
            return new JGithubCredentialsPath(alias, this);
        }

        @Override
        public JGithubCredentialsPath as(Table<?> alias) {
            return new JGithubCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_GITHUB_CREDENTIALS_USER_ID, Indexes.IDX_GITHUB_CREDENTIALS_USER_UNIQUE);
    }

    @Override
    public UniqueKey<JGithubCredentialsRecord> getPrimaryKey() {
        return Keys.GITHUB_CREDENTIALS_PKEY;
    }

    @Override
    public List<ForeignKey<JGithubCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GITHUB_CREDENTIALS__GITHUB_CREDENTIALS_USER_ID_FKEY);
    }

    private transient JUsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public JUsersPath users() {
        if (_users == null)
            _users = new JUsersPath(this, Keys.GITHUB_CREDENTIALS__GITHUB_CREDENTIALS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public JGithubCredentials as(String alias) {
        return new JGithubCredentials(DSL.name(alias), this);
    }

    @Override
    public JGithubCredentials as(Name alias) {
        return new JGithubCredentials(alias, this);
    }

    @Override
    public JGithubCredentials as(Table<?> alias) {
        return new JGithubCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JGithubCredentials rename(String name) {
        return new JGithubCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JGithubCredentials rename(Name name) {
        return new JGithubCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JGithubCredentials rename(Table<?> name) {
        return new JGithubCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials where(Condition condition) {
        return new JGithubCredentials(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JGithubCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JGithubCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JGithubCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JGithubCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JGithubCredentials whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, UUID, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
