/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.JPublic;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.tables.JUsers.JUsersPath;
import com.example.backend.jooq.tables.records.JNotionCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JNotionCredentials extends TableImpl<JNotionCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notion_credentials</code>
     */
    public static final JNotionCredentials NOTION_CREDENTIALS = new JNotionCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JNotionCredentialsRecord> getRecordType() {
        return JNotionCredentialsRecord.class;
    }

    /**
     * The column <code>public.notion_credentials.id</code>.
     */
    public final TableField<JNotionCredentialsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.notion_credentials.user_id</code>.
     */
    public final TableField<JNotionCredentialsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notion_credentials.api_key</code>.
     */
    public final TableField<JNotionCredentialsRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.notion_credentials.database_id</code>.
     */
    public final TableField<JNotionCredentialsRecord, String> DATABASE_ID = createField(DSL.name("database_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.notion_credentials.title_property</code>.
     */
    public final TableField<JNotionCredentialsRecord, String> TITLE_PROPERTY = createField(DSL.name("title_property"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.notion_credentials.status_property</code>.
     */
    public final TableField<JNotionCredentialsRecord, String> STATUS_PROPERTY = createField(DSL.name("status_property"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.notion_credentials.date_property</code>.
     */
    public final TableField<JNotionCredentialsRecord, String> DATE_PROPERTY = createField(DSL.name("date_property"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.notion_credentials.filter_conditions</code>.
     */
    public final TableField<JNotionCredentialsRecord, JSONB> FILTER_CONDITIONS = createField(DSL.name("filter_conditions"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.notion_credentials.is_active</code>.
     */
    public final TableField<JNotionCredentialsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.notion_credentials.created_at</code>.
     */
    public final TableField<JNotionCredentialsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.notion_credentials.updated_at</code>.
     */
    public final TableField<JNotionCredentialsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private JNotionCredentials(Name alias, Table<JNotionCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JNotionCredentials(Name alias, Table<JNotionCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.notion_credentials</code> table reference
     */
    public JNotionCredentials(String alias) {
        this(DSL.name(alias), NOTION_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.notion_credentials</code> table reference
     */
    public JNotionCredentials(Name alias) {
        this(alias, NOTION_CREDENTIALS);
    }

    /**
     * Create a <code>public.notion_credentials</code> table reference
     */
    public JNotionCredentials() {
        this(DSL.name("notion_credentials"), null);
    }

    public <O extends Record> JNotionCredentials(Table<O> path, ForeignKey<O, JNotionCredentialsRecord> childPath, InverseForeignKey<O, JNotionCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, NOTION_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JNotionCredentialsPath extends JNotionCredentials implements Path<JNotionCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JNotionCredentialsPath(Table<O> path, ForeignKey<O, JNotionCredentialsRecord> childPath, InverseForeignKey<O, JNotionCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JNotionCredentialsPath(Name alias, Table<JNotionCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JNotionCredentialsPath as(String alias) {
            return new JNotionCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public JNotionCredentialsPath as(Name alias) {
            return new JNotionCredentialsPath(alias, this);
        }

        @Override
        public JNotionCredentialsPath as(Table<?> alias) {
            return new JNotionCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTION_CREDENTIALS_USER_ID, Indexes.IDX_NOTION_CREDENTIALS_USER_UNIQUE);
    }

    @Override
    public UniqueKey<JNotionCredentialsRecord> getPrimaryKey() {
        return Keys.NOTION_CREDENTIALS_PKEY;
    }

    @Override
    public List<ForeignKey<JNotionCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTION_CREDENTIALS__NOTION_CREDENTIALS_USER_ID_FKEY);
    }

    private transient JUsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public JUsersPath users() {
        if (_users == null)
            _users = new JUsersPath(this, Keys.NOTION_CREDENTIALS__NOTION_CREDENTIALS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public JNotionCredentials as(String alias) {
        return new JNotionCredentials(DSL.name(alias), this);
    }

    @Override
    public JNotionCredentials as(Name alias) {
        return new JNotionCredentials(alias, this);
    }

    @Override
    public JNotionCredentials as(Table<?> alias) {
        return new JNotionCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JNotionCredentials rename(String name) {
        return new JNotionCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JNotionCredentials rename(Name name) {
        return new JNotionCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JNotionCredentials rename(Table<?> name) {
        return new JNotionCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials where(Condition condition) {
        return new JNotionCredentials(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JNotionCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JNotionCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JNotionCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JNotionCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JNotionCredentials whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, UUID, String, String, String, String, String, JSONB, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
