/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.JPublic;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.tables.JUsers.JUsersPath;
import com.example.backend.jooq.tables.records.JReportTemplatesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JReportTemplates extends TableImpl<JReportTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_templates</code>
     */
    public static final JReportTemplates REPORT_TEMPLATES = new JReportTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JReportTemplatesRecord> getRecordType() {
        return JReportTemplatesRecord.class;
    }

    /**
     * The column <code>public.report_templates.id</code>.
     */
    public final TableField<JReportTemplatesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.report_templates.user_id</code>.
     */
    public final TableField<JReportTemplatesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.report_templates.name</code>.
     */
    public final TableField<JReportTemplatesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.report_templates.format_structure</code>.
     */
    public final TableField<JReportTemplatesRecord, JSONB> FORMAT_STRUCTURE = createField(DSL.name("format_structure"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.report_templates.is_default</code>.
     */
    public final TableField<JReportTemplatesRecord, Boolean> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.report_templates.created_at</code>.
     */
    public final TableField<JReportTemplatesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.report_templates.updated_at</code>.
     */
    public final TableField<JReportTemplatesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private JReportTemplates(Name alias, Table<JReportTemplatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JReportTemplates(Name alias, Table<JReportTemplatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_templates</code> table reference
     */
    public JReportTemplates(String alias) {
        this(DSL.name(alias), REPORT_TEMPLATES);
    }

    /**
     * Create an aliased <code>public.report_templates</code> table reference
     */
    public JReportTemplates(Name alias) {
        this(alias, REPORT_TEMPLATES);
    }

    /**
     * Create a <code>public.report_templates</code> table reference
     */
    public JReportTemplates() {
        this(DSL.name("report_templates"), null);
    }

    public <O extends Record> JReportTemplates(Table<O> path, ForeignKey<O, JReportTemplatesRecord> childPath, InverseForeignKey<O, JReportTemplatesRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_TEMPLATES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JReportTemplatesPath extends JReportTemplates implements Path<JReportTemplatesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JReportTemplatesPath(Table<O> path, ForeignKey<O, JReportTemplatesRecord> childPath, InverseForeignKey<O, JReportTemplatesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JReportTemplatesPath(Name alias, Table<JReportTemplatesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JReportTemplatesPath as(String alias) {
            return new JReportTemplatesPath(DSL.name(alias), this);
        }

        @Override
        public JReportTemplatesPath as(Name alias) {
            return new JReportTemplatesPath(alias, this);
        }

        @Override
        public JReportTemplatesPath as(Table<?> alias) {
            return new JReportTemplatesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REPORT_TEMPLATES_USER_ID);
    }

    @Override
    public UniqueKey<JReportTemplatesRecord> getPrimaryKey() {
        return Keys.REPORT_TEMPLATES_PKEY;
    }

    @Override
    public List<ForeignKey<JReportTemplatesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_TEMPLATES__REPORT_TEMPLATES_USER_ID_FKEY);
    }

    private transient JUsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public JUsersPath users() {
        if (_users == null)
            _users = new JUsersPath(this, Keys.REPORT_TEMPLATES__REPORT_TEMPLATES_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public JReportTemplates as(String alias) {
        return new JReportTemplates(DSL.name(alias), this);
    }

    @Override
    public JReportTemplates as(Name alias) {
        return new JReportTemplates(alias, this);
    }

    @Override
    public JReportTemplates as(Table<?> alias) {
        return new JReportTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JReportTemplates rename(String name) {
        return new JReportTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JReportTemplates rename(Name name) {
        return new JReportTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JReportTemplates rename(Table<?> name) {
        return new JReportTemplates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates where(Condition condition) {
        return new JReportTemplates(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JReportTemplates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JReportTemplates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JReportTemplates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JReportTemplates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JReportTemplates whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, JSONB, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super UUID, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super UUID, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
