/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.Public;
import com.example.backend.jooq.tables.Users.UsersPath;
import com.example.backend.jooq.tables.records.ReportTemplatesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportTemplates extends TableImpl<ReportTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_templates</code>
     */
    public static final ReportTemplates REPORT_TEMPLATES = new ReportTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportTemplatesRecord> getRecordType() {
        return ReportTemplatesRecord.class;
    }

    /**
     * The column <code>public.report_templates.id</code>.
     */
    public final TableField<ReportTemplatesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.report_templates.user_id</code>.
     */
    public final TableField<ReportTemplatesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.report_templates.name</code>.
     */
    public final TableField<ReportTemplatesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.report_templates.format_structure</code>.
     */
    public final TableField<ReportTemplatesRecord, JSONB> FORMAT_STRUCTURE = createField(DSL.name("format_structure"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.report_templates.is_default</code>.
     */
    public final TableField<ReportTemplatesRecord, Boolean> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.report_templates.created_at</code>.
     */
    public final TableField<ReportTemplatesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.report_templates.updated_at</code>.
     */
    public final TableField<ReportTemplatesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private ReportTemplates(Name alias, Table<ReportTemplatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReportTemplates(Name alias, Table<ReportTemplatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_templates</code> table reference
     */
    public ReportTemplates(String alias) {
        this(DSL.name(alias), REPORT_TEMPLATES);
    }

    /**
     * Create an aliased <code>public.report_templates</code> table reference
     */
    public ReportTemplates(Name alias) {
        this(alias, REPORT_TEMPLATES);
    }

    /**
     * Create a <code>public.report_templates</code> table reference
     */
    public ReportTemplates() {
        this(DSL.name("report_templates"), null);
    }

    public <O extends Record> ReportTemplates(Table<O> path, ForeignKey<O, ReportTemplatesRecord> childPath, InverseForeignKey<O, ReportTemplatesRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_TEMPLATES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReportTemplatesPath extends ReportTemplates implements Path<ReportTemplatesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReportTemplatesPath(Table<O> path, ForeignKey<O, ReportTemplatesRecord> childPath, InverseForeignKey<O, ReportTemplatesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReportTemplatesPath(Name alias, Table<ReportTemplatesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReportTemplatesPath as(String alias) {
            return new ReportTemplatesPath(DSL.name(alias), this);
        }

        @Override
        public ReportTemplatesPath as(Name alias) {
            return new ReportTemplatesPath(alias, this);
        }

        @Override
        public ReportTemplatesPath as(Table<?> alias) {
            return new ReportTemplatesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REPORT_TEMPLATES_USER_ID);
    }

    @Override
    public UniqueKey<ReportTemplatesRecord> getPrimaryKey() {
        return Keys.REPORT_TEMPLATES_PKEY;
    }

    @Override
    public List<ForeignKey<ReportTemplatesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_TEMPLATES__REPORT_TEMPLATES_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.REPORT_TEMPLATES__REPORT_TEMPLATES_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public ReportTemplates as(String alias) {
        return new ReportTemplates(DSL.name(alias), this);
    }

    @Override
    public ReportTemplates as(Name alias) {
        return new ReportTemplates(alias, this);
    }

    @Override
    public ReportTemplates as(Table<?> alias) {
        return new ReportTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportTemplates rename(String name) {
        return new ReportTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportTemplates rename(Name name) {
        return new ReportTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportTemplates rename(Table<?> name) {
        return new ReportTemplates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates where(Condition condition) {
        return new ReportTemplates(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportTemplates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportTemplates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportTemplates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportTemplates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportTemplates whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, JSONB, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super UUID, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super UUID, ? super String, ? super JSONB, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
