/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables;


import com.example.backend.jooq.Indexes;
import com.example.backend.jooq.Keys;
import com.example.backend.jooq.Public;
import com.example.backend.jooq.tables.Users.UsersPath;
import com.example.backend.jooq.tables.records.TogglCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TogglCredentials extends TableImpl<TogglCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.toggl_credentials</code>
     */
    public static final TogglCredentials TOGGL_CREDENTIALS = new TogglCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TogglCredentialsRecord> getRecordType() {
        return TogglCredentialsRecord.class;
    }

    /**
     * The column <code>public.toggl_credentials.id</code>.
     */
    public final TableField<TogglCredentialsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.toggl_credentials.user_id</code>.
     */
    public final TableField<TogglCredentialsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.toggl_credentials.api_key</code>.
     */
    public final TableField<TogglCredentialsRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.toggl_credentials.workspace_id</code>.
     */
    public final TableField<TogglCredentialsRecord, Long> WORKSPACE_ID = createField(DSL.name("workspace_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.toggl_credentials.project_ids</code>.
     */
    public final TableField<TogglCredentialsRecord, Integer[]> PROJECT_IDS = createField(DSL.name("project_ids"), SQLDataType.INTEGER.array(), this, "");

    /**
     * The column <code>public.toggl_credentials.default_tags</code>.
     */
    public final TableField<TogglCredentialsRecord, String[]> DEFAULT_TAGS = createField(DSL.name("default_tags"), SQLDataType.CLOB.array(), this, "");

    /**
     * The column <code>public.toggl_credentials.time_zone</code>.
     */
    public final TableField<TogglCredentialsRecord, String> TIME_ZONE = createField(DSL.name("time_zone"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'UTC'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.toggl_credentials.include_weekends</code>.
     */
    public final TableField<TogglCredentialsRecord, Boolean> INCLUDE_WEEKENDS = createField(DSL.name("include_weekends"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.toggl_credentials.is_active</code>.
     */
    public final TableField<TogglCredentialsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.toggl_credentials.created_at</code>.
     */
    public final TableField<TogglCredentialsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.toggl_credentials.updated_at</code>.
     */
    public final TableField<TogglCredentialsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private TogglCredentials(Name alias, Table<TogglCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TogglCredentials(Name alias, Table<TogglCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.toggl_credentials</code> table reference
     */
    public TogglCredentials(String alias) {
        this(DSL.name(alias), TOGGL_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.toggl_credentials</code> table reference
     */
    public TogglCredentials(Name alias) {
        this(alias, TOGGL_CREDENTIALS);
    }

    /**
     * Create a <code>public.toggl_credentials</code> table reference
     */
    public TogglCredentials() {
        this(DSL.name("toggl_credentials"), null);
    }

    public <O extends Record> TogglCredentials(Table<O> path, ForeignKey<O, TogglCredentialsRecord> childPath, InverseForeignKey<O, TogglCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, TOGGL_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TogglCredentialsPath extends TogglCredentials implements Path<TogglCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TogglCredentialsPath(Table<O> path, ForeignKey<O, TogglCredentialsRecord> childPath, InverseForeignKey<O, TogglCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TogglCredentialsPath(Name alias, Table<TogglCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TogglCredentialsPath as(String alias) {
            return new TogglCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public TogglCredentialsPath as(Name alias) {
            return new TogglCredentialsPath(alias, this);
        }

        @Override
        public TogglCredentialsPath as(Table<?> alias) {
            return new TogglCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TOGGL_CREDENTIALS_USER_ID, Indexes.IDX_TOGGL_CREDENTIALS_USER_UNIQUE);
    }

    @Override
    public UniqueKey<TogglCredentialsRecord> getPrimaryKey() {
        return Keys.TOGGL_CREDENTIALS_PKEY;
    }

    @Override
    public List<ForeignKey<TogglCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TOGGL_CREDENTIALS__TOGGL_CREDENTIALS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.TOGGL_CREDENTIALS__TOGGL_CREDENTIALS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public TogglCredentials as(String alias) {
        return new TogglCredentials(DSL.name(alias), this);
    }

    @Override
    public TogglCredentials as(Name alias) {
        return new TogglCredentials(alias, this);
    }

    @Override
    public TogglCredentials as(Table<?> alias) {
        return new TogglCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TogglCredentials rename(String name) {
        return new TogglCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TogglCredentials rename(Name name) {
        return new TogglCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TogglCredentials rename(Table<?> name) {
        return new TogglCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials where(Condition condition) {
        return new TogglCredentials(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TogglCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TogglCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TogglCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TogglCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TogglCredentials whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, UUID, String, Long, Integer[], String[], String, Boolean, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super UUID, ? super UUID, ? super String, ? super Long, ? super Integer[], ? super String[], ? super String, ? super Boolean, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super UUID, ? super UUID, ? super String, ? super Long, ? super Integer[], ? super String[], ? super String, ? super Boolean, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
