/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.JApiCredentials;
import com.example.backend.jooq.tables.JDailyReports;
import com.example.backend.jooq.tables.JFlywaySchemaHistory;
import com.example.backend.jooq.tables.JGenerationLogs;
import com.example.backend.jooq.tables.JReportTemplates;
import com.example.backend.jooq.tables.JUsers;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_API_CREDENTIALS_SERVICE_TYPE = Internal.createIndex(DSL.name("idx_api_credentials_service_type"), JApiCredentials.API_CREDENTIALS, new OrderField[] { JApiCredentials.API_CREDENTIALS.SERVICE_TYPE }, false);
    public static final Index IDX_API_CREDENTIALS_USER_ID = Internal.createIndex(DSL.name("idx_api_credentials_user_id"), JApiCredentials.API_CREDENTIALS, new OrderField[] { JApiCredentials.API_CREDENTIALS.USER_ID }, false);
    public static final Index IDX_API_CREDENTIALS_USER_SERVICE = Internal.createIndex(DSL.name("idx_api_credentials_user_service"), JApiCredentials.API_CREDENTIALS, new OrderField[] { JApiCredentials.API_CREDENTIALS.USER_ID, JApiCredentials.API_CREDENTIALS.SERVICE_TYPE }, true);
    public static final Index IDX_DAILY_REPORTS_REPORT_DATE = Internal.createIndex(DSL.name("idx_daily_reports_report_date"), JDailyReports.DAILY_REPORTS, new OrderField[] { JDailyReports.DAILY_REPORTS.REPORT_DATE }, false);
    public static final Index IDX_DAILY_REPORTS_USER_DATE = Internal.createIndex(DSL.name("idx_daily_reports_user_date"), JDailyReports.DAILY_REPORTS, new OrderField[] { JDailyReports.DAILY_REPORTS.USER_ID, JDailyReports.DAILY_REPORTS.REPORT_DATE }, true);
    public static final Index IDX_DAILY_REPORTS_USER_ID = Internal.createIndex(DSL.name("idx_daily_reports_user_id"), JDailyReports.DAILY_REPORTS, new OrderField[] { JDailyReports.DAILY_REPORTS.USER_ID }, false);
    public static final Index IDX_GENERATION_LOGS_REPORT_ID = Internal.createIndex(DSL.name("idx_generation_logs_report_id"), JGenerationLogs.GENERATION_LOGS, new OrderField[] { JGenerationLogs.GENERATION_LOGS.REPORT_ID }, false);
    public static final Index IDX_REPORT_TEMPLATES_USER_ID = Internal.createIndex(DSL.name("idx_report_templates_user_id"), JReportTemplates.REPORT_TEMPLATES, new OrderField[] { JReportTemplates.REPORT_TEMPLATES.USER_ID }, false);
    public static final Index IDX_USERS_EMAIL = Internal.createIndex(DSL.name("idx_users_email"), JUsers.USERS, new OrderField[] { JUsers.USERS.EMAIL }, false);
}
