/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.DailyReports;
import com.example.backend.jooq.tables.FlywaySchemaHistory;
import com.example.backend.jooq.tables.GenerationLogs;
import com.example.backend.jooq.tables.GithubCredentials;
import com.example.backend.jooq.tables.NotionCredentials;
import com.example.backend.jooq.tables.ReportTemplates;
import com.example.backend.jooq.tables.TogglCredentials;
import com.example.backend.jooq.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_DAILY_REPORTS_REPORT_DATE = Internal.createIndex(DSL.name("idx_daily_reports_report_date"), DailyReports.DAILY_REPORTS, new OrderField[] { DailyReports.DAILY_REPORTS.REPORT_DATE }, false);
    public static final Index IDX_DAILY_REPORTS_USER_DATE = Internal.createIndex(DSL.name("idx_daily_reports_user_date"), DailyReports.DAILY_REPORTS, new OrderField[] { DailyReports.DAILY_REPORTS.USER_ID, DailyReports.DAILY_REPORTS.REPORT_DATE }, true);
    public static final Index IDX_DAILY_REPORTS_USER_ID = Internal.createIndex(DSL.name("idx_daily_reports_user_id"), DailyReports.DAILY_REPORTS, new OrderField[] { DailyReports.DAILY_REPORTS.USER_ID }, false);
    public static final Index IDX_GENERATION_LOGS_REPORT_ID = Internal.createIndex(DSL.name("idx_generation_logs_report_id"), GenerationLogs.GENERATION_LOGS, new OrderField[] { GenerationLogs.GENERATION_LOGS.REPORT_ID }, false);
    public static final Index IDX_GITHUB_CREDENTIALS_USER_ID = Internal.createIndex(DSL.name("idx_github_credentials_user_id"), GithubCredentials.GITHUB_CREDENTIALS, new OrderField[] { GithubCredentials.GITHUB_CREDENTIALS.USER_ID }, false);
    public static final Index IDX_GITHUB_CREDENTIALS_USER_UNIQUE = Internal.createIndex(DSL.name("idx_github_credentials_user_unique"), GithubCredentials.GITHUB_CREDENTIALS, new OrderField[] { GithubCredentials.GITHUB_CREDENTIALS.USER_ID }, true);
    public static final Index IDX_NOTION_CREDENTIALS_USER_ID = Internal.createIndex(DSL.name("idx_notion_credentials_user_id"), NotionCredentials.NOTION_CREDENTIALS, new OrderField[] { NotionCredentials.NOTION_CREDENTIALS.USER_ID }, false);
    public static final Index IDX_NOTION_CREDENTIALS_USER_UNIQUE = Internal.createIndex(DSL.name("idx_notion_credentials_user_unique"), NotionCredentials.NOTION_CREDENTIALS, new OrderField[] { NotionCredentials.NOTION_CREDENTIALS.USER_ID }, true);
    public static final Index IDX_REPORT_TEMPLATES_USER_ID = Internal.createIndex(DSL.name("idx_report_templates_user_id"), ReportTemplates.REPORT_TEMPLATES, new OrderField[] { ReportTemplates.REPORT_TEMPLATES.USER_ID }, false);
    public static final Index IDX_TOGGL_CREDENTIALS_USER_ID = Internal.createIndex(DSL.name("idx_toggl_credentials_user_id"), TogglCredentials.TOGGL_CREDENTIALS, new OrderField[] { TogglCredentials.TOGGL_CREDENTIALS.USER_ID }, false);
    public static final Index IDX_TOGGL_CREDENTIALS_USER_UNIQUE = Internal.createIndex(DSL.name("idx_toggl_credentials_user_unique"), TogglCredentials.TOGGL_CREDENTIALS, new OrderField[] { TogglCredentials.TOGGL_CREDENTIALS.USER_ID }, true);
    public static final Index IDX_USERS_EMAIL = Internal.createIndex(DSL.name("idx_users_email"), Users.USERS, new OrderField[] { Users.USERS.EMAIL }, false);
}
