/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.JApiCredentials;
import com.example.backend.jooq.tables.JDailyReports;
import com.example.backend.jooq.tables.JFlywaySchemaHistory;
import com.example.backend.jooq.tables.JGenerationLogs;
import com.example.backend.jooq.tables.JReportTemplates;
import com.example.backend.jooq.tables.JUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JPublic extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final JPublic PUBLIC = new JPublic();

    /**
     * The table <code>public.api_credentials</code>.
     */
    public final JApiCredentials API_CREDENTIALS = JApiCredentials.API_CREDENTIALS;

    /**
     * The table <code>public.daily_reports</code>.
     */
    public final JDailyReports DAILY_REPORTS = JDailyReports.DAILY_REPORTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final JFlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.generation_logs</code>.
     */
    public final JGenerationLogs GENERATION_LOGS = JGenerationLogs.GENERATION_LOGS;

    /**
     * The table <code>public.report_templates</code>.
     */
    public final JReportTemplates REPORT_TEMPLATES = JReportTemplates.REPORT_TEMPLATES;

    /**
     * The table <code>public.users</code>.
     */
    public final JUsers USERS = JUsers.USERS;

    /**
     * No further instances allowed
     */
    private JPublic() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JApiCredentials.API_CREDENTIALS,
            JDailyReports.DAILY_REPORTS,
            JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            JGenerationLogs.GENERATION_LOGS,
            JReportTemplates.REPORT_TEMPLATES,
            JUsers.USERS
        );
    }
}
