/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.DailyReports;
import com.example.backend.jooq.tables.FlywaySchemaHistory;
import com.example.backend.jooq.tables.GenerationLogs;
import com.example.backend.jooq.tables.GithubCredentials;
import com.example.backend.jooq.tables.NotionCredentials;
import com.example.backend.jooq.tables.ReportTemplates;
import com.example.backend.jooq.tables.TogglCredentials;
import com.example.backend.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.daily_reports</code>.
     */
    public static final DailyReports DAILY_REPORTS = DailyReports.DAILY_REPORTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.generation_logs</code>.
     */
    public static final GenerationLogs GENERATION_LOGS = GenerationLogs.GENERATION_LOGS;

    /**
     * The table <code>public.github_credentials</code>.
     */
    public static final GithubCredentials GITHUB_CREDENTIALS = GithubCredentials.GITHUB_CREDENTIALS;

    /**
     * The table <code>public.notion_credentials</code>.
     */
    public static final NotionCredentials NOTION_CREDENTIALS = NotionCredentials.NOTION_CREDENTIALS;

    /**
     * The table <code>public.report_templates</code>.
     */
    public static final ReportTemplates REPORT_TEMPLATES = ReportTemplates.REPORT_TEMPLATES;

    /**
     * The table <code>public.toggl_credentials</code>.
     */
    public static final TogglCredentials TOGGL_CREDENTIALS = TogglCredentials.TOGGL_CREDENTIALS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
