/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.JApiCredentials;
import com.example.backend.jooq.tables.JDailyReports;
import com.example.backend.jooq.tables.JFlywaySchemaHistory;
import com.example.backend.jooq.tables.JGenerationLogs;
import com.example.backend.jooq.tables.JReportTemplates;
import com.example.backend.jooq.tables.JUsers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.api_credentials</code>.
     */
    public static final JApiCredentials API_CREDENTIALS = JApiCredentials.API_CREDENTIALS;

    /**
     * The table <code>public.daily_reports</code>.
     */
    public static final JDailyReports DAILY_REPORTS = JDailyReports.DAILY_REPORTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final JFlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.generation_logs</code>.
     */
    public static final JGenerationLogs GENERATION_LOGS = JGenerationLogs.GENERATION_LOGS;

    /**
     * The table <code>public.report_templates</code>.
     */
    public static final JReportTemplates REPORT_TEMPLATES = JReportTemplates.REPORT_TEMPLATES;

    /**
     * The table <code>public.users</code>.
     */
    public static final JUsers USERS = JUsers.USERS;
}
