/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.JDailyReports;
import com.example.backend.jooq.tables.JFlywaySchemaHistory;
import com.example.backend.jooq.tables.JGithubCredentials;
import com.example.backend.jooq.tables.JNotionCredentials;
import com.example.backend.jooq.tables.JReportTemplates;
import com.example.backend.jooq.tables.JTogglCredentials;
import com.example.backend.jooq.tables.JUsers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.daily_reports</code>.
     */
    public static final JDailyReports DAILY_REPORTS = JDailyReports.DAILY_REPORTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final JFlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.github_credentials</code>.
     */
    public static final JGithubCredentials GITHUB_CREDENTIALS = JGithubCredentials.GITHUB_CREDENTIALS;

    /**
     * The table <code>public.notion_credentials</code>.
     */
    public static final JNotionCredentials NOTION_CREDENTIALS = JNotionCredentials.NOTION_CREDENTIALS;

    /**
     * The table <code>public.report_templates</code>.
     */
    public static final JReportTemplates REPORT_TEMPLATES = JReportTemplates.REPORT_TEMPLATES;

    /**
     * The table <code>public.toggl_credentials</code>.
     */
    public static final JTogglCredentials TOGGL_CREDENTIALS = JTogglCredentials.TOGGL_CREDENTIALS;

    /**
     * The table <code>public.users</code>.
     */
    public static final JUsers USERS = JUsers.USERS;
}
