/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.GithubCredentials;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubCredentialsRecord extends UpdatableRecordImpl<GithubCredentialsRecord> implements Record9<UUID, UUID, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.github_credentials.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.github_credentials.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.github_credentials.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.github_credentials.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.github_credentials.api_key</code>.
     */
    public void setApiKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.github_credentials.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.github_credentials.base_url</code>.
     */
    public void setBaseUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.github_credentials.base_url</code>.
     */
    public String getBaseUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.github_credentials.owner</code>.
     */
    public void setOwner(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.github_credentials.owner</code>.
     */
    public String getOwner() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.github_credentials.repo</code>.
     */
    public void setRepo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.github_credentials.repo</code>.
     */
    public String getRepo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.github_credentials.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.github_credentials.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.github_credentials.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.github_credentials.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.github_credentials.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.github_credentials.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, UUID, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, UUID, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return GithubCredentials.GITHUB_CREDENTIALS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return GithubCredentials.GITHUB_CREDENTIALS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return GithubCredentials.GITHUB_CREDENTIALS.API_KEY;
    }

    @Override
    public Field<String> field4() {
        return GithubCredentials.GITHUB_CREDENTIALS.BASE_URL;
    }

    @Override
    public Field<String> field5() {
        return GithubCredentials.GITHUB_CREDENTIALS.OWNER;
    }

    @Override
    public Field<String> field6() {
        return GithubCredentials.GITHUB_CREDENTIALS.REPO;
    }

    @Override
    public Field<Boolean> field7() {
        return GithubCredentials.GITHUB_CREDENTIALS.IS_ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return GithubCredentials.GITHUB_CREDENTIALS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return GithubCredentials.GITHUB_CREDENTIALS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getApiKey();
    }

    @Override
    public String component4() {
        return getBaseUrl();
    }

    @Override
    public String component5() {
        return getOwner();
    }

    @Override
    public String component6() {
        return getRepo();
    }

    @Override
    public Boolean component7() {
        return getIsActive();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getApiKey();
    }

    @Override
    public String value4() {
        return getBaseUrl();
    }

    @Override
    public String value5() {
        return getOwner();
    }

    @Override
    public String value6() {
        return getRepo();
    }

    @Override
    public Boolean value7() {
        return getIsActive();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public GithubCredentialsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value3(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value4(String value) {
        setBaseUrl(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value5(String value) {
        setOwner(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value6(String value) {
        setRepo(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value7(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GithubCredentialsRecord values(UUID value1, UUID value2, String value3, String value4, String value5, String value6, Boolean value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubCredentialsRecord
     */
    public GithubCredentialsRecord() {
        super(GithubCredentials.GITHUB_CREDENTIALS);
    }

    /**
     * Create a detached, initialised GithubCredentialsRecord
     */
    public GithubCredentialsRecord(UUID id, UUID userId, String apiKey, String baseUrl, String owner, String repo, Boolean isActive, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(GithubCredentials.GITHUB_CREDENTIALS);

        setId(id);
        setUserId(userId);
        setApiKey(apiKey);
        setBaseUrl(baseUrl);
        setOwner(owner);
        setRepo(repo);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
