/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.JDailyReports;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JDailyReportsRecord extends UpdatableRecordImpl<JDailyReportsRecord> implements Record12<UUID, UUID, LocalDate, JSONB, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.daily_reports.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.daily_reports.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.daily_reports.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.daily_reports.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.daily_reports.report_date</code>.
     */
    public void setReportDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.daily_reports.report_date</code>.
     */
    public LocalDate getReportDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.daily_reports.raw_data</code>.
     */
    public void setRawData(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.daily_reports.raw_data</code>.
     */
    public JSONB getRawData() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.daily_reports.generated_content</code>.
     */
    public void setGeneratedContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.daily_reports.generated_content</code>.
     */
    public String getGeneratedContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.daily_reports.edited_content</code>.
     */
    public void setEditedContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.daily_reports.edited_content</code>.
     */
    public String getEditedContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.daily_reports.final_content</code>.
     */
    public void setFinalContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.daily_reports.final_content</code>.
     */
    public String getFinalContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.daily_reports.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.daily_reports.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.daily_reports.generation_count</code>.
     */
    public void setGenerationCount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.daily_reports.generation_count</code>.
     */
    public Integer getGenerationCount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.daily_reports.additional_notes</code>.
     */
    public void setAdditionalNotes(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.daily_reports.additional_notes</code>.
     */
    public String getAdditionalNotes() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.daily_reports.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.daily_reports.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.daily_reports.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.daily_reports.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, UUID, LocalDate, JSONB, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<UUID, UUID, LocalDate, JSONB, String, String, String, String, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JDailyReports.DAILY_REPORTS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return JDailyReports.DAILY_REPORTS.USER_ID;
    }

    @Override
    public Field<LocalDate> field3() {
        return JDailyReports.DAILY_REPORTS.REPORT_DATE;
    }

    @Override
    public Field<JSONB> field4() {
        return JDailyReports.DAILY_REPORTS.RAW_DATA;
    }

    @Override
    public Field<String> field5() {
        return JDailyReports.DAILY_REPORTS.GENERATED_CONTENT;
    }

    @Override
    public Field<String> field6() {
        return JDailyReports.DAILY_REPORTS.EDITED_CONTENT;
    }

    @Override
    public Field<String> field7() {
        return JDailyReports.DAILY_REPORTS.FINAL_CONTENT;
    }

    @Override
    public Field<String> field8() {
        return JDailyReports.DAILY_REPORTS.STATUS;
    }

    @Override
    public Field<Integer> field9() {
        return JDailyReports.DAILY_REPORTS.GENERATION_COUNT;
    }

    @Override
    public Field<String> field10() {
        return JDailyReports.DAILY_REPORTS.ADDITIONAL_NOTES;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return JDailyReports.DAILY_REPORTS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return JDailyReports.DAILY_REPORTS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public LocalDate component3() {
        return getReportDate();
    }

    @Override
    public JSONB component4() {
        return getRawData();
    }

    @Override
    public String component5() {
        return getGeneratedContent();
    }

    @Override
    public String component6() {
        return getEditedContent();
    }

    @Override
    public String component7() {
        return getFinalContent();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public Integer component9() {
        return getGenerationCount();
    }

    @Override
    public String component10() {
        return getAdditionalNotes();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public LocalDate value3() {
        return getReportDate();
    }

    @Override
    public JSONB value4() {
        return getRawData();
    }

    @Override
    public String value5() {
        return getGeneratedContent();
    }

    @Override
    public String value6() {
        return getEditedContent();
    }

    @Override
    public String value7() {
        return getFinalContent();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public Integer value9() {
        return getGenerationCount();
    }

    @Override
    public String value10() {
        return getAdditionalNotes();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedAt();
    }

    @Override
    public JDailyReportsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value3(LocalDate value) {
        setReportDate(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value4(JSONB value) {
        setRawData(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value5(String value) {
        setGeneratedContent(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value6(String value) {
        setEditedContent(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value7(String value) {
        setFinalContent(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value9(Integer value) {
        setGenerationCount(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value10(String value) {
        setAdditionalNotes(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value11(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value12(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public JDailyReportsRecord values(UUID value1, UUID value2, LocalDate value3, JSONB value4, String value5, String value6, String value7, String value8, Integer value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDailyReportsRecord
     */
    public JDailyReportsRecord() {
        super(JDailyReports.DAILY_REPORTS);
    }

    /**
     * Create a detached, initialised JDailyReportsRecord
     */
    public JDailyReportsRecord(UUID id, UUID userId, LocalDate reportDate, JSONB rawData, String generatedContent, String editedContent, String finalContent, String status, Integer generationCount, String additionalNotes, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(JDailyReports.DAILY_REPORTS);

        setId(id);
        setUserId(userId);
        setReportDate(reportDate);
        setRawData(rawData);
        setGeneratedContent(generatedContent);
        setEditedContent(editedContent);
        setFinalContent(finalContent);
        setStatus(status);
        setGenerationCount(generationCount);
        setAdditionalNotes(additionalNotes);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
