/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.JDailyReports;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JDailyReportsRecord extends UpdatableRecordImpl<JDailyReportsRecord> implements Record8<UUID, UUID, LocalDate, JSONB, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.daily_reports.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.daily_reports.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.daily_reports.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.daily_reports.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.daily_reports.report_date</code>.
     */
    public void setReportDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.daily_reports.report_date</code>.
     */
    public LocalDate getReportDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.daily_reports.raw_data</code>.
     */
    public void setRawData(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.daily_reports.raw_data</code>.
     */
    public JSONB getRawData() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.daily_reports.final_content</code>.
     */
    public void setFinalContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.daily_reports.final_content</code>.
     */
    public String getFinalContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.daily_reports.additional_notes</code>.
     */
    public void setAdditionalNotes(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.daily_reports.additional_notes</code>.
     */
    public String getAdditionalNotes() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.daily_reports.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.daily_reports.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.daily_reports.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.daily_reports.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, LocalDate, JSONB, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, UUID, LocalDate, JSONB, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JDailyReports.DAILY_REPORTS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return JDailyReports.DAILY_REPORTS.USER_ID;
    }

    @Override
    public Field<LocalDate> field3() {
        return JDailyReports.DAILY_REPORTS.REPORT_DATE;
    }

    @Override
    public Field<JSONB> field4() {
        return JDailyReports.DAILY_REPORTS.RAW_DATA;
    }

    @Override
    public Field<String> field5() {
        return JDailyReports.DAILY_REPORTS.FINAL_CONTENT;
    }

    @Override
    public Field<String> field6() {
        return JDailyReports.DAILY_REPORTS.ADDITIONAL_NOTES;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JDailyReports.DAILY_REPORTS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JDailyReports.DAILY_REPORTS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public LocalDate component3() {
        return getReportDate();
    }

    @Override
    public JSONB component4() {
        return getRawData();
    }

    @Override
    public String component5() {
        return getFinalContent();
    }

    @Override
    public String component6() {
        return getAdditionalNotes();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public LocalDate value3() {
        return getReportDate();
    }

    @Override
    public JSONB value4() {
        return getRawData();
    }

    @Override
    public String value5() {
        return getFinalContent();
    }

    @Override
    public String value6() {
        return getAdditionalNotes();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public JDailyReportsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value3(LocalDate value) {
        setReportDate(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value4(JSONB value) {
        setRawData(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value5(String value) {
        setFinalContent(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value6(String value) {
        setAdditionalNotes(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public JDailyReportsRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public JDailyReportsRecord values(UUID value1, UUID value2, LocalDate value3, JSONB value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JDailyReportsRecord
     */
    public JDailyReportsRecord() {
        super(JDailyReports.DAILY_REPORTS);
    }

    /**
     * Create a detached, initialised JDailyReportsRecord
     */
    public JDailyReportsRecord(UUID id, UUID userId, LocalDate reportDate, JSONB rawData, String finalContent, String additionalNotes, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(JDailyReports.DAILY_REPORTS);

        setId(id);
        setUserId(userId);
        setReportDate(reportDate);
        setRawData(rawData);
        setFinalContent(finalContent);
        setAdditionalNotes(additionalNotes);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
