/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.ReportTemplates;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportTemplatesRecord extends UpdatableRecordImpl<ReportTemplatesRecord> implements Record7<UUID, UUID, String, JSONB, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_templates.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_templates.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.report_templates.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_templates.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.report_templates.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_templates.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report_templates.format_structure</code>.
     */
    public void setFormatStructure(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report_templates.format_structure</code>.
     */
    public JSONB getFormatStructure() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.report_templates.is_default</code>.
     */
    public void setIsDefault(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report_templates.is_default</code>.
     */
    public Boolean getIsDefault() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.report_templates.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.report_templates.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.report_templates.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.report_templates.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, JSONB, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, String, JSONB, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ReportTemplates.REPORT_TEMPLATES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return ReportTemplates.REPORT_TEMPLATES.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return ReportTemplates.REPORT_TEMPLATES.NAME;
    }

    @Override
    public Field<JSONB> field4() {
        return ReportTemplates.REPORT_TEMPLATES.FORMAT_STRUCTURE;
    }

    @Override
    public Field<Boolean> field5() {
        return ReportTemplates.REPORT_TEMPLATES.IS_DEFAULT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ReportTemplates.REPORT_TEMPLATES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ReportTemplates.REPORT_TEMPLATES.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public JSONB component4() {
        return getFormatStructure();
    }

    @Override
    public Boolean component5() {
        return getIsDefault();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public JSONB value4() {
        return getFormatStructure();
    }

    @Override
    public Boolean value5() {
        return getIsDefault();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public ReportTemplatesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value4(JSONB value) {
        setFormatStructure(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value5(Boolean value) {
        setIsDefault(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ReportTemplatesRecord values(UUID value1, UUID value2, String value3, JSONB value4, Boolean value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportTemplatesRecord
     */
    public ReportTemplatesRecord() {
        super(ReportTemplates.REPORT_TEMPLATES);
    }

    /**
     * Create a detached, initialised ReportTemplatesRecord
     */
    public ReportTemplatesRecord(UUID id, UUID userId, String name, JSONB formatStructure, Boolean isDefault, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ReportTemplates.REPORT_TEMPLATES);

        setId(id);
        setUserId(userId);
        setName(name);
        setFormatStructure(formatStructure);
        setIsDefault(isDefault);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
