/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.TogglCredentials;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TogglCredentialsRecord extends UpdatableRecordImpl<TogglCredentialsRecord> implements Record11<UUID, UUID, String, Long, Integer[], String[], String, Boolean, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.toggl_credentials.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.toggl_credentials.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.toggl_credentials.api_key</code>.
     */
    public void setApiKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.toggl_credentials.workspace_id</code>.
     */
    public void setWorkspaceId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.workspace_id</code>.
     */
    public Long getWorkspaceId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.toggl_credentials.project_ids</code>.
     */
    public void setProjectIds(Integer[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.project_ids</code>.
     */
    public Integer[] getProjectIds() {
        return (Integer[]) get(4);
    }

    /**
     * Setter for <code>public.toggl_credentials.default_tags</code>.
     */
    public void setDefaultTags(String[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.default_tags</code>.
     */
    public String[] getDefaultTags() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>public.toggl_credentials.time_zone</code>.
     */
    public void setTimeZone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.time_zone</code>.
     */
    public String getTimeZone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.toggl_credentials.include_weekends</code>.
     */
    public void setIncludeWeekends(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.include_weekends</code>.
     */
    public Boolean getIncludeWeekends() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.toggl_credentials.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.toggl_credentials.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.toggl_credentials.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.toggl_credentials.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, UUID, String, Long, Integer[], String[], String, Boolean, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, UUID, String, Long, Integer[], String[], String, Boolean, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return TogglCredentials.TOGGL_CREDENTIALS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return TogglCredentials.TOGGL_CREDENTIALS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return TogglCredentials.TOGGL_CREDENTIALS.API_KEY;
    }

    @Override
    public Field<Long> field4() {
        return TogglCredentials.TOGGL_CREDENTIALS.WORKSPACE_ID;
    }

    @Override
    public Field<Integer[]> field5() {
        return TogglCredentials.TOGGL_CREDENTIALS.PROJECT_IDS;
    }

    @Override
    public Field<String[]> field6() {
        return TogglCredentials.TOGGL_CREDENTIALS.DEFAULT_TAGS;
    }

    @Override
    public Field<String> field7() {
        return TogglCredentials.TOGGL_CREDENTIALS.TIME_ZONE;
    }

    @Override
    public Field<Boolean> field8() {
        return TogglCredentials.TOGGL_CREDENTIALS.INCLUDE_WEEKENDS;
    }

    @Override
    public Field<Boolean> field9() {
        return TogglCredentials.TOGGL_CREDENTIALS.IS_ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return TogglCredentials.TOGGL_CREDENTIALS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return TogglCredentials.TOGGL_CREDENTIALS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getApiKey();
    }

    @Override
    public Long component4() {
        return getWorkspaceId();
    }

    @Override
    public Integer[] component5() {
        return getProjectIds();
    }

    @Override
    public String[] component6() {
        return getDefaultTags();
    }

    @Override
    public String component7() {
        return getTimeZone();
    }

    @Override
    public Boolean component8() {
        return getIncludeWeekends();
    }

    @Override
    public Boolean component9() {
        return getIsActive();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getApiKey();
    }

    @Override
    public Long value4() {
        return getWorkspaceId();
    }

    @Override
    public Integer[] value5() {
        return getProjectIds();
    }

    @Override
    public String[] value6() {
        return getDefaultTags();
    }

    @Override
    public String value7() {
        return getTimeZone();
    }

    @Override
    public Boolean value8() {
        return getIncludeWeekends();
    }

    @Override
    public Boolean value9() {
        return getIsActive();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public TogglCredentialsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value3(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value4(Long value) {
        setWorkspaceId(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value5(Integer[] value) {
        setProjectIds(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value6(String[] value) {
        setDefaultTags(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value7(String value) {
        setTimeZone(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value8(Boolean value) {
        setIncludeWeekends(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value9(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord value11(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TogglCredentialsRecord values(UUID value1, UUID value2, String value3, Long value4, Integer[] value5, String[] value6, String value7, Boolean value8, Boolean value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TogglCredentialsRecord
     */
    public TogglCredentialsRecord() {
        super(TogglCredentials.TOGGL_CREDENTIALS);
    }

    /**
     * Create a detached, initialised TogglCredentialsRecord
     */
    public TogglCredentialsRecord(UUID id, UUID userId, String apiKey, Long workspaceId, Integer[] projectIds, String[] defaultTags, String timeZone, Boolean includeWeekends, Boolean isActive, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(TogglCredentials.TOGGL_CREDENTIALS);

        setId(id);
        setUserId(userId);
        setApiKey(apiKey);
        setWorkspaceId(workspaceId);
        setProjectIds(projectIds);
        setDefaultTags(defaultTags);
        setTimeZone(timeZone);
        setIncludeWeekends(includeWeekends);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
